name: PCBridge
website: https://github.com/projectcitybuild/PCBridge
version: 6.8.0
api-version: 1.21.1
main: com.projectcitybuild.pcbridge.paper.Plugin
bootstrapper: com.projectcitybuild.pcbridge.paper.PaperBootstrap
loader: com.projectcitybuild.pcbridge.paper.PaperLoader

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    dynmap:
      load: BEFORE
      required: true
      join-classpath: true
    Essentials:
      load: BEFORE
      required: false
      join-classpath: true