name: PCBridge
main: com.projectcitybuild.pcbridge.paper.Plugin
website: https://github.com/projectcitybuild/PCBridge
author: Andy
version: 6.4.0
api-version: 1.20

softdepend:
  - LuckPerms
  - dynmap
  - Essentials

commands:
  warp:
    permission: pcbridge.warps.teleport
  warps:
    permission: pcbridge.warps.list