main: com.projectcitybuild.platforms.spigot.SpigotPlatform
name: PCBridge
version: 3.0.2
softdepend:
  - LuckPerms

api-version: 1.16

libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:1.5.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:1.5.0

commands:
  setwarp:
    description: "Creates a warp at the current position and direction"
    permission: "pcbridge.warp.create"
    usage: "/setwarp <name>"
  sethub:
    description: "Sets the destination of the /hub command at the current position and direction"
    permission: "pcbridge.hub.set"
    usage: "/sethub"