name: PCBridge
main: com.pcb.pcbridge.PCBridge
version: 1.0.0
depend: [Vault]

commands:
  ban:
    description: Permanently bans the specified player from the server.
    usage: /<command> [player] [reason]
    permission: pcbridge.ban.ban
  unban:
    description: Unbans the specified player.
    usage: /<command> [player]
    permission: pcbridge.ban.unban
  checkban:
    description: Checks if the specified player is currently banned.
    usage: /<command> [player]
    permission: pcbridge.ban.checkban
  lookup:
    description: Checks if the specified player is currently banned.
    usage: /<command> [player]
    permission: pcbridge.ban.lookup
  uuid:
    description: Retrieves UUID data about a player from Mojang's web service
    usage: /<command> [history|uuid] [player]
    permission: pcbridge.ban.uuid
  pcbridge:
    description: Utility commands
    usage: /<command> [key] [value]
    permission: pcbridge.utility
  buyhead:
    description: Purchases the head of the specified player
    usage: /<command> player:[name] [quantity]
    permission: pcbridge.economy.buyhead