main: com.projectcitybuild.platforms.spigot.SpigotPlatform
name: PCBridge
version: 3.4.0
softdepend:
  - LuckPerms

api-version: 1.16

libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:1.5.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:1.5.0

commands:
  delwarp:
    description: "Deletes a warp"
    usage: "/delwarp <name>"
  setwarp:
    description: "Creates a warp at the current position and direction"
    permission: "pcbridge.warp.create"
    usage: "/setwarp <name>"
  sethub:
    description: "Sets the destination of the /hub command at the current position and direction"
    permission: "pcbridge.hub.set"
    usage: "/sethub"
  warp:
    description: "Teleports to a pre-defined location"
    usage: "/warp <name>"
  warps:
    description: "Gets a list of all warps available"
    usage: "/warps"