name: PCBridge
main: com.pcb.pcbridge.PCBridge
version: 3.0.0
website: https://projectcitybuild.com
description: Bridges PCB game servers with the website

commands:
  maintenance:
    description: De/activates service maintenance mode
    usage: "/maintenance [on|off]"
    permission: pcbridge.maintenance.set
  mute:
    description: Prevents a player from chatting (can still use commands)
    usage: "/mute <name>"
    permission: pcbridge.chat.mute
  unmute:
      description: Allows a player to chat again
      usage: "/unmute <name>"
      permission: pcbridge.chat.mute