main: com.projectcitybuild.PCBridge
name: PCBridge
version: 2.2.0
softdepend: [Vault, PermissionsEX]

commands:
   maintenance:
      description: Toggles 'Maintenance Mode' on the server, allowing only staff to connect
      usage: /maintenance [on|off] [message]
   mute:
      description: Prevents a player from chatting
      usage: /mute <name>
   unmute:
      description: Removes a chat mute on a player
      usage: /unmute <name>
   prefix:
      description: Sets (or gets) the prefix of a player
      usage: |
         /prefix <name> set <prefix>
         /prefix <name> clear
         /prefix <name>
   suffix:
      description: Sets (or gets) the suffix of a player
      usage: |
         /suffix <name> set <suffix>
         /suffix <name> clear
         /suffix <name>
   ban:
      description: Globally bans a player from connecting to any PCB game servers
      usage: /ban <name> [reason]
   unban:
      description: Globally unbans a player from all PCB game servers
      usage: /unban <name>
   checkban:
      description: Checks the ban status of the given player
      usage: /checkban <name>
   sync:
      description: Syncs your Minecraft account rank with your PCB account
      usage: /sync [finish]