main: com.projectcitybuild.platforms.spigot.SpigotPlatform
name: PCBridge
version: 2.6.0
softdepend:
  - LuckPerms

api-version: 1.16

commands:
   maintenance:
      description: Toggles 'Maintenance Mode' on the server, allowing only staff to connect
      usage: /maintenance [on|off] [message]
   mute:
      description: Prevents a player from chatting
      usage: /mute <name>
   unmute:
      description: Removes a chat mute on a player
      usage: /unmute <name>
   ban:
      description: Globally bans a player from connecting to any PCB game servers
      usage: /ban <name> [reason]
   unban:
      description: Globally unbans a player from all PCB game servers
      usage: /unban <name>
   checkban:
      description: Checks the ban status of the given player
      usage: /checkban <name>
   sync:
      description: Syncs your Minecraft account rank with your PCB account
      usage: /sync [finish]
   box:
      description: Views available mystery boxes for donors, or redeems them once per day
      usage: /box [redeem]
