main: com.projectcitybuild.PCBridge
name: PCBridge
version: 1.0.0

commands:
   maintenance:
      description: Toggles 'Maintenance Mode' on the server, allowing only staff to connect
      usage: /maintenance [on|off] [message]
   mute:
      description: Prevents a player from chatting
      usage: /mute <name>
   unmute:
      description: Removes a chat mute on a player
      usage: /unmute <name>
   ban:
      description: Globally bans a player from connecting to any PCB game servers
      usage: /ban <name> [reason]
   status:
      description: Checks the ban status of the given player
      usage: /status <name>