name: setup-java

description: Installs Java and Gradle, then restores the Gradle dependencies from cache

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@f4f1212c880fdec8162ea9a6493f4495191887b4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
