name: PCBridge
main: com.projectcitybuild.PCBridge
website: https://github.com/projectcitybuild/PCBridge
author: Andy
version: 6.0.0
api-version: 1.20

softdepend:
  - LuckPerms
  - dynmap
  - Essentials

commands:
  a:
    permission: pcbridge.chat.staff_channel
  mute:
    permission: pcbridge.chat.mute
  pcbridge:
    permission: pcbridge.utils
  invisframe:
    permission: pcbridge.build.invisframe
  nv:
    permission: pcbridge.build.nightvision
  unmute:
    permission: pcbridge.chat.mute
  warp:
    permission: pcbridge.warps.teleport
  warps:
    permission: pcbridge.warps.list