main: com.projectcitybuild.PCBridge
name: PCBridge
author: Andy
version: 5.0.0
softdepend:
  - LuckPerms
  - dynmap
  - GadgetsMenu
  - Essentials

api-version: 1.16

commands:
  a:
    description: "Sends a message to all staff currently online"
    usage: "/a"
  ban:
    description: "Bans a player from connecting to the server"
    usage: "/ban <name> [reason]"
  badge:
    description: "Toggles on/off your chat badge"
    usage: "/badge <on|off>"
  banip:
    description: "Bans an exact IP, preventing it from connecting to the server"
    usage: "/ban <ip|name> <reason>"
  checkban:
    description: "Checks whether a player is currently banned from the server"
    usage: "/checkban <name>"
  delwarp:
    description: "Deletes a warp"
    usage: "/delwarp <name>"
  mute:
    description: "Prevents a player from talking in chat"
    usage: "/mute <name>"
  pcbridge:
    description: "Shows the plugin version or runs utility commands"
    usage: "/pcbridge <version|import>"
  setwarp:
    description: "Creates a warp at the current position and direction"
    permission: "pcbridge.warp.create"
    usage: "/setwarp <name>"
  sync:
    description: "Syncs your rank with the website"
    usage: "/sync [finish]"
  syncother:
    description: "Syncs a given player's rank with the website"
    usage: "/syncother <name>"
  unban:
    description: "Allows a banned player to connect to the server"
    usage: "/unban <name>"
  unbanip:
    description: "Allows the given IP to connect to the server"
    usage: "/unbanip <ip>"
  unmute:
    description: "Allows a muted player to talk in chat again"
    usage: "/unmute"
  warp:
    description: "Teleports to a pre-defined location"
    usage: "/warp <name>"
  warps:
    description: "Gets a list of all warps available"
    usage: "/warps"
  warning:
    description: "Acknowledges a given warning"
    usage: "/warning acknowledge <id>"
