name: PCBridge
main: com.projectcitybuild.PCBridge
website: https://github.com/projectcitybuild/PCBridge
author: Andy
version: 6.0.0
api-version: 1.20

softdepend:
  - LuckPerms
  - dynmap
  - Essentials

commands:
  warp:
    permissions: pcbridge.warps.teleport
  warps:
    permissions: pcbridge.warps.list
  pcbridge:
    permissions: pcbridge.utils