main: com.projectcitybuild.PCBridge
name: PCBridge
author: Andy
version: 5.0.0
softdepend:
  - LuckPerms
  - dynmap
  - GadgetsMenu
  - Essentials

api-version: 1.16

commands:
  a:
    description: "Sends a message to all staff currently online"
    usage: "/a"
  delwarp:
    description: "Deletes a warp"
    usage: "/delwarp <name>"
  mute:
    description: "Prevents a player from talking in chat"
    usage: "/mute <name>"
  pcbridge:
    description: "Shows the plugin version or runs utility commands"
    usage: "/pcbridge <version|import>"
  setwarp:
    description: "Creates a warp at the current position and direction"
    permission: "pcbridge.warp.create"
    usage: "/setwarp <name>"
  sync:
    description: "Syncs your rank with the website"
    usage: "/sync [finish]"
  syncother:
    description: "Syncs a given player's rank with the website"
    usage: "/syncother <name>"
  unmute:
    description: "Allows a muted player to talk in chat again"
    usage: "/unmute"
  warp:
    description: "Teleports to a pre-defined location"
    usage: "/warp <name>"
  warps:
    description: "Gets a list of all warps available"
    usage: "/warps"
  warning:
    description: "Acknowledges a given warning"
    usage: "/warning acknowledge <id>"
