main: com.projectcitybuild.PCBridge
name: PCBridge
author: Andy
version: 6.0.0
api-version: 1.16

softdepend:
  - LuckPerms
  - dynmap
  - Essentials

commands:
  warp:
    permissions: pcbridge.warps.teleport
  warps:
    permissions: pcbridge.warps.list
  pcbridge:
    permissions: pcbridge.utils