name: Run tests

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: ./.github/actions/setup-java

      - name: Run tests
        run: gradle test --info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          use_oidc: true
          files: "**/build/reports/jacoco/test/jacocoTestReport.xml"
          report_type: test_results
          fail_ci_if_error: true